### ISSUE TITLE
Please choose a proper license for this project

### ISSUE THREAD

**Issue by AnimiVulpis** [signavio/configuration-provider#3]
If you want to use an open source license may I suggest the *Blue Oak Model License 1.0.0*.
A few reason why to use this license are pointed out [here](https://blueoakcouncil.org/2019/03/06/model.html)

**Comment by adelolmo** [comment]
MIT comes a requirement from Nico.

**Comment by sskras** [comment]
Umm, who or what is Nico? : )

**Comment by adelolmo** [comment]
MIT license added.

> Umm, who or what is Nico? : )
 
Our CTO.
